<?php
/**
 * @file
 * Code for the Drupal Camp Ottawa Modify Form Feature
 */

 /**
 * Implements hook_form_alter().
 * Or use hook_form_FORM_ID_alter()
 */
function dco_d7_module_form_alter(&$form, &$form_state, $form_id) {
  // Change fields based on campaign status
  if ($form_id == 'dco_form_id') {

    // Add field lock validator
    $form['#validate'][] = '_dco_d7_module_validate_publish_form';

    //check if published
    $lock_fields = _dco_d7_module_locked_on_publish();
    foreach ($lock_fields as $field) {
      $form[$field]['#disabled'] = TRUE;
    }
  }
}


function _dco_d7_module_validate_publish_form($form, $form_state) {

}

/**
 * Locked field on publishing
 */
function _dco_d7_module_locked_on_publish($form, $form_state) {
  return array(
    'title',
    'body',    
  );
}